name: Deploy DAGs to Composer

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        type: string
    secrets:
      gcp_sa_key:
        description: 'GCP service account key JSON'
        required: true

jobs:
  deploy-dags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.gcp_sa_key }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Check for DAG files
        id: check_dags
        run: |
          if [ -n "$(ls -A dags/*.py 2>/dev/null)" ]; then
            echo "has_dags=true" >> $GITHUB_OUTPUT
            echo "Found DAG files:"
            ls -1 dags/*.py
          else
            echo "has_dags=false" >> $GITHUB_OUTPUT
            echo "No DAG files found in dags/ directory"
          fi

      - name: Upload DAGs to Composer bucket
        if: steps.check_dags.outputs.has_dags == 'true'
        run: |
          gcloud storage cp \
            "dags/*.py" \
            gs://mlsys-composer-${{ inputs.environment }}/dags/

      - name: Verify deployment
        if: steps.check_dags.outputs.has_dags == 'true'
        run: |
          echo "DAGs deployed successfully to ${{ inputs.environment }}"
          echo "Bucket: gs://mlsys-composer-${{ inputs.environment }}/dags/"
          ls -1 dags/*.py
