name: Deploy DAG to Composer

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod
      dag_name:
        description: 'DAG filename (e.g., titanic_survival_dag.py)'
        required: true
        type: string

jobs:
  deploy-dag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.SA }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Validate DAG file exists
        run: |
          if [ ! -f "dags/${{ github.event.inputs.dag_name }}" ]; then
            echo "Error: DAG file dags/${{ github.event.inputs.dag_name }} not found"
            exit 1
          fi

      - name: Upload DAG to Composer bucket
        run: |
          gcloud storage cp \
            dags/${{ github.event.inputs.dag_name }} \
            gs://mlsys-composer-${{ github.event.inputs.environment }}/dags/

      - name: Verify deployment
        run: |
          echo "DAG deployed successfully to ${{ github.event.inputs.environment }}"
          echo "File: ${{ github.event.inputs.dag_name }}"
          echo "Bucket: gs://mlsys-composer-${{ github.event.inputs.environment }}/dags/"
