name: Docker Build and Push

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to (dev, staging, prod)'
        required: true
        type: string
      image_tag:
        description: 'Docker image tag (e.g., git SHA or version)'
        required: true
        type: string

jobs:
  docker-build:
    name: Build and push Docker (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: gcp
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ vars.GCP_REGION }}'
          echo '${{ secrets.GCP_SA_KEY }}' > ${HOME}/gcp-key.json
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ vars.GCP_PROJECT_ID }}
          rm ${HOME}/gcp-key.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          FULL_IMAGE_TAG="${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/mlsys-${{ inputs.environment }}/mlsys-${{ inputs.environment }}:${{ inputs.image_tag }}"
          docker build -t $FULL_IMAGE_TAG .
          docker push $FULL_IMAGE_TAG
