name: PR - Dev Deployment

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --group pre-commit

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

  # check-changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     infra_changed: ${{ steps.filter.outputs.infra }}
  #     code_changed: ${{ steps.filter.outputs.code }}
  #     cloud_funcs_changed: ${{ steps.filter.outputs.cloud_funcs }}
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Check for changes
  #       uses: dorny/paths-filter@v3
  #       id: filter
  #       with:
  #         filters: |
  #           infra:
  #             - 'infra/**'
  #           code:
  #             - 'src/**'
  #             - 'mlsys/**'
  #             - 'cloud_runs/**'
  #             - 'pyproject.toml'
  #             - 'uv.lock'
  #             - 'Dockerfile'
  #             - '.dockerignore'
  #           cloud_funcs:
  #             - 'cloud_funcs/**'

  # terraform-dev:
  #   needs: [pre-commit]
  #   uses: ./.github/workflows/terraform.yml
  #   with:
  #     environment: dev
  #     terraform_action: apply
  #     gcp_region: ${{ vars.GCP_REGION }}
  #     gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
  #   secrets:
  #     gcp_sa_key: ${{ secrets.GCP_SA_KEY }}

  docker-dev:
    needs: [pre-commit]
    if: always()
    uses: ./.github/workflows/docker.yml
    with:
      environment: dev
      image_tag: ${{ github.sha }}

  cloud-functions-dev:
    needs: [pre-commit]
    if: always()
    uses: ./.github/workflows/cloud_functions.yml
    with:
      environment: dev
    secrets:
      gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
