name: PR - Dev Deployment

on:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

  check-changes:
    runs-on: ubuntu-latest
    outputs:
      infra_changed: ${{ steps.filter.outputs.infra }}
      code_changed: ${{ steps.filter.outputs.code }}
      dags_changed: ${{ steps.filter.outputs.dags }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            infra:
              - 'infra/**'
            code:
              - 'src/**'
              - 'mlsys/**'
              - 'scripts/**'
              - 'pyproject.toml'
              - 'uv.lock'
              - 'Dockerfile'
              - '.dockerignore'
            dags:
              - 'dags/**'

  terraform-dev:
    needs: [pre-commit, check-changes]
    if: needs.check-changes.outputs.infra_changed == 'true'
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      terraform_action: apply
      gcp_region: ${{ vars.GCP_REGION }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      gcp_sa_key: ${{ secrets.SA }}

  docker-dev:
    needs: [check-changes, terraform-dev]
    if: |
      always() &&
      needs.check-changes.outputs.code_changed == 'true' &&
      (needs.terraform-dev.result == 'success' || needs.terraform-dev.result == 'skipped')
    uses: ./.github/workflows/docker.yml
    with:
      environment: dev
      image_tag: ${{ github.sha }}
      gcp_region: ${{ vars.GCP_REGION }}
      gcp_project_id: ${{ vars.GCP_PROJECT_ID }}
    secrets:
      gcp_sa_key: ${{ secrets.SA }}

  airflow-dev:
    needs: [check-changes, terraform-dev]
    if: |
      always() &&
      needs.check-changes.outputs.dags_changed == 'true' &&
      (needs.terraform-dev.result == 'success' || needs.terraform-dev.result == 'skipped')
    uses: ./.github/workflows/airflow.yml
    with:
      environment: dev
    secrets:
      gcp_sa_key: ${{ secrets.SA }}
